apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cache-image-pipelinerun-
  labels:
    app.kubernetes.io/description: PipelineRun
  namespace: default
spec:
  params:
  - name: BUILDER_IMAGE
    value: docker.io/cnbs/sample-builder:bionic@sha256:6c03dd604503b59820fd15adbc65c0a077a47e31d404a3dcad190f3179e920b5
  - name: TRUST_BUILDER
    value: "true"
  - name: APP_IMAGE
    value: ttl.sh/slsa
  - name: imageUrl
    value: ttl.sh/slsa
  - name: imageTag
    value: latest
  - name: SOURCE_URL
    value: https://github.com/buildpacks/samples
  - name: SOURCE_SUBPATH
    value: apps/ruby-bundler
  - name: CACHE_IMAGE
    value: ttl.sh/slsa-cache
  pipelineRef:
    name: buildpacks
  workspaces:
  - name: source-ws
    persistentVolumeClaim:
      claimName: cache-image-pipelinerun-source-ws-pvc
    subPath: source
  - emptyDir: {}
    name: cache-ws
