apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-image-pipelinerun-source-ws-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
